PACKAGE_NAME="wireguard"
PACKAGE_VERSION="1.0"
BUILT_MODULE_NAME[0]="wireguard"
DEST_MODULE_LOCATION[0]="/updates"
AUTOINSTALL="yes"
MAKE[0]="make kernel CONFIG_MODULE_COMPRESS_XZ=n"
BUILT_MODULE_LOCATION[0]="wireguard-linux/"
CLEAN="make clean"
